# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14dd263226d6cd8d7be61af6f6f6163d1b1ac06764db275046cd925b5d4a7b93d0597594609c65caf83ccd295cf9eea95715f94328c7ba4206c6f44ae51b2025

test:
  secret_key_base: cbf0b206c436ea2e9066a5b78a2b234a93e76099ef37ff32cbce0cd2a2240bfae601d002f970f0ab81a945ecd8d3a07c228caff86d061320995b7f9e0ab848f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
